### ISSUE TITLE
ㅁㄴㅇ

### ISSUE THREAD

**Issue by gkrnwl** [d07RiV/diabloweb#101]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.18 (Shareware)

**Error message:**
    
    Error: Invalid spawn.mpq size. Try clearing cache and refreshing the page.
        at https://d07riv.github.io/diabloweb/static/js/main.af57bee7.chunk.js:1:1882
        at c (https://d07riv.github.io/diabloweb/static/js/0.54f3d658.chunk.js:1:10071)
        at Generator._invoke (https://d07riv.github.io/diabloweb/static/js/0.54f3d658.chunk.js:1:9859)
        at Generator.t.<computed> [as next] (https://d07riv.github.io/diabloweb/static/js/0.54f3d658.chunk.js:1:10493)
        at n (https://d07riv.github.io/diabloweb/static/js/0.54f3d658.chunk.js:1:8313)
        at u (https://d07riv.github.io/diabloweb/static/js/0.54f3d658.chunk.js:1:8515)

**User agent:**

    Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
Please describe what you were doing before the error occurred
