### ISSUE TITLE
1

### ISSUE THREAD

**Issue by jURA720** [d07RiV/diabloweb#102]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Retail)

**Error message:**
    
    Error: Main program archive: diabdat.mpq
        at Error (api/game.worker.js:86:10)
        at exit_error (api/Diablo.jscc:1645:135)
        at __Z14api_exit_errorPKc (wasm-function[190]:0xfd01)
        at __Z9app_fatalPKcz (wasm-function[192]:0xfd60)
        at _DApi_Init (wasm-function[1277]:0xd4fc8)
        at apply (api/Diablo.jscc:2442:0)
        at https://d07riv.github.io/diabloweb/b6959098d798174bd69f.worker.js?__WB_REVISION__=84295573488973f434291055ed9bbbff:1:79171
        at call (../node_modules/regenerator-runtime/runtime.js:45:0)
        at tryCatch (../node_modules/regenerator-runtime/runtime.js:264:0)
        at _invoke (../node_modules/regenerator-runtime/runtime.js:98:0)

**User agent:**

    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
With out a description this is unfortunately not helpful
