### ISSUE TITLE
Error with my MPQ file

### ISSUE THREAD

**Issue by serviet666** [d07RiV/diabloweb#103]
**Description:**
Trying to use my MPQ file.

**App version:**
DiabloWeb 1.0.39 (Retail)

**Error message:**
    
    Error: Main program archive: diabdat.mpq
        at Error (api/game.worker.js:86:10)
        at exit_error (api/Diablo.jscc:1645:135)
        at __Z14api_exit_errorPKc (wasm-function[190]:3)
        at __Z9app_fatalPKcz (wasm-function[192]:43)
        at _DApi_Init (wasm-function[1277]:202)
        at apply (api/Diablo.jscc:2442:0)
        at https://d07riv.github.io/diabloweb/b6959098d798174bd69f.worker.js?__WB_REVISION__=84295573488973f434291055ed9bbbff:1:79171
        at call (../node_modules/regenerator-runtime/runtime.js:45:0)
        at tryCatch (../node_modules/regenerator-runtime/runtime.js:264:0)
        at _invoke (../node_modules/regenerator-runtime/runtime.js:98:0)

**User agent:**

    Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Save file:**
Can't attach my MPQ file...

**Comment by AJenbo** [comment]
What's the md5 sum of your mpq

**Comment by serviet666** [comment]
It seems to be `5c4867f4ee488e7c64703f9eb9c083a2`

**Comment by AJenbo** [comment]
That is the wrong file (it's the 37KB patch_rt.mpq), the correct one is called diabdat.mpq and is about 518MB.

**Comment by serviet666** [comment]
This is the only MPQ file in my Diablo folder...

**Comment by AJenbo** [comment]
If you have the original game (not from GOG) then the file is on your CD.

**Comment by serviet666** [comment]
Forget it, i've just found it in the CD root folder... ! Thanks !

**Comment by serviet666** [comment]
Yeah right, i was searching in my setup folder...

**Comment by serviet666** [comment]
So cool from you, thanks for your help.
