### ISSUE TITLE
Files aren't loading for some reason

### ISSUE THREAD

**Issue by A12509188** [d07RiV/diabloweb#105]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.13 (Shareware)

**Error message:**
    
    Error: Failed to construct 'Worker': Script at 'file:///home/chronos/u-2c9f067cfc73f202be99d599648c77accfb69cf3/MyFiles/Downloads/emupedia.github.io-master/beta/emuos/vfat/games/diablo1/9232376d1969e7a9ebae.worker.js' cannot be accessed from origin 'null'.
        at new e.exports (file:///home/chronos/u-2c9f067cfc73f202be99d599648c77accfb69cf3/MyFiles/Downloads/emupedia.github.io-master/beta/emuos/vfat/games/diablo1/static/js/main.26aae697.chunk.js:4:11)
        at file:///home/chronos/u-2c9f067cfc73f202be99d599648c77accfb69cf3/MyFiles/Downloads/emupedia.github.io-master/beta/emuos/vfat/games/diablo1/static/js/main.26aae697.chunk.js:147:18
        at new Promise (<anonymous>)
        at file:///home/chronos/u-2c9f067cfc73f202be99d599648c77accfb69cf3/MyFiles/Downloads/emupedia.github.io-master/beta/emuos/vfat/games/diablo1/static/js/main.26aae697.chunk.js:145:90
        at c (file:///home/chronos/u-2c9f067cfc73f202be99d599648c77accfb69cf3/MyFiles/Downloads/emupedia.github.io-master/beta/emuos/vfat/games/diablo1/static/js/0.54f3d658.chunk.js:379:37)
        at Generator._invoke (file:///home/chronos/u-2c9f067cfc73f202be99d599648c77accfb69cf3/MyFiles/Downloads/emupedia.github.io-master/beta/emuos/vfat/games/diablo1/static/js/0.54f3d658.chunk.js:366:16)
        at Generator.t.<computed> [as next] (file:///home/chronos/u-2c9f067cfc73f202be99d599648c77accfb69cf3/MyFiles/Downloads/emupedia.github.io-master/beta/emuos/vfat/games/diablo1/static/js/0.54f3d658.chunk.js:408:19)
        at n (file:///home/chronos/u-2c9f067cfc73f202be99d599648c77accfb69cf3/MyFiles/Downloads/emupedia.github.io-master/beta/emuos/vfat/games/diablo1/static/js/0.54f3d658.chunk.js:280:17)
        at u (file:///home/chronos/u-2c9f067cfc73f202be99d599648c77accfb69cf3/MyFiles/Downloads/emupedia.github.io-master/beta/emuos/vfat/games/diablo1/static/js/0.54f3d658.chunk.js:294:7)

**Comment by AJenbo** [comment]
What files?
