### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MoRRoM99** [d07RiV/diabloweb#119]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    ReferenceError: WebAssembly is not defined
        at wasmMemory (api/DiabloSpawn.jscc:1239:0)
        at spawn (api/game.worker.js:358:24)
        at fn (../node_modules/regenerator-runtime/runtime.js:45:0)
        at tryCatch (../node_modules/regenerator-runtime/runtime.js:264:0)
        at this (../node_modules/regenerator-runtime/runtime.js:98:0)
        at gen (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:0)
        at asyncGeneratorStep (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:0)
    

**User agent:**

    Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]
