### ISSUE TITLE
diablo 1 network error

### ISSUE THREAD

**Issue by Nomaverick** [d07RiV/diabloweb#137]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.13 (Shareware)

**Error message:**
    
    Error: Network Error
        at e.exports (https://emupedia.net/emupedia-game-diablo1/static/js/5.473ccc28.chunk.js:636:11)
        at XMLHttpRequest.d.onerror (https://emupedia.net/emupedia-game-diablo1/static/js/5.473ccc28.chunk.js:613:7)

**Comment by AJenbo** [comment]
We have nothing to do with emupedia.net, they have an old version, use the latest instead: https://d07riv.github.io/diabloweb/
