### ISSUE TITLE
leocrack

### ISSUE THREAD

**Issue by leckov** [d07RiV/diabloweb#139]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    Network Error
        at e.exports (../node_modules/axios/lib/core/createError.js:17:0)
        at createError (../node_modules/axios/lib/adapters/xhr.js:80:0)

**User agent:**

    Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]

**Comment by SpiralBrad** [comment]
Good thing you included the User agent, this would be useless without it.

lol

**Comment by AJenbo** [comment]
that's done automatically by the crash handling
