### ISSUE TITLE
GOG

### ISSUE THREAD

**Issue by Leeiyll** [d07RiV/diabloweb#155]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    invalid MPQ file
        at https://d07riv.github.io/diabloweb/static/js/main.62369ba5.chunk.js?__WB_REVISION__=4bfb1f4cbbd7e8ddffcd:1:34674
        at call (../node_modules/regenerator-runtime/runtime.js:45:0)
        at tryCatch (../node_modules/regenerator-runtime/runtime.js:264:0)
        at _invoke (../node_modules/regenerator-runtime/runtime.js:98:0)
        at arg (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:0)
        at asyncGeneratorStep (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:0)

**User agent:**

    Mozilla/5.0 (Linux; Android 8.0.0; ASUS_X00RD) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.101 Mobile Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]

**Comment by AJenbo** [comment]
In case your problem hasn't been solved I would suggest you try the native Android app instead.
oi
https://play.google.com/store/apps/details?id=org.diasurgical.devilutionx
