### ISSUE TITLE
Can't load diabdat.mpq

### ISSUE THREAD

**Issue by cojack** [d07RiV/diabloweb#184]
**Description:**
I just select the DIABDAT.MPQ with sha1 276bd81782a155c52fe19aa08b3579970e307e7e

**App version:**
DiabloWeb 1.0.39 (Retail)

**Error message:**
    
    Error: Main program archive: diabdat.mpq
        at Error (api/game.worker.js:86:10)
        at exit_error (api/Diablo.jscc:1645:135)
    __Z14api_exit_errorPKc@https://playclassic.games/diabloweb/9438624a921118f473b8.worker.js?__WB_REVISION__=1bb157da2a824692da268b0ceac61cf3 line 1 > WebAssembly.instantiate:wasm-function[190]:0xfd01
    __Z9app_fatalPKcz@https://playclassic.games/diabloweb/9438624a921118f473b8.worker.js?__WB_REVISION__=1bb157da2a824692da268b0ceac61cf3 line 1 > WebAssembly.instantiate:wasm-function[192]:0xfd60
    _DApi_Init@https://playclassic.games/diabloweb/9438624a921118f473b8.worker.js?__WB_REVISION__=1bb157da2a824692da268b0ceac61cf3 line 1 > WebAssembly.instantiate:wasm-function[1277]:0xd4fc8
        at apply (api/Diablo.jscc:2442:0)
        at _DApi_Init (api/game.worker.js:407:7)
        at call (../node_modules/regenerator-runtime/runtime.js:45:0)
        at innerFn (../node_modules/regenerator-runtime/runtime.js:264:0)
        at _invoke (../node_modules/regenerator-runtime/runtime.js:98:0)
        at arg (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:0)
        at gen (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:0)
    

**User agent:**

    Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0

**Save file:**
Not related
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
Sorry but could you do an md5 instead I only have a list of valid md5 values :)

**Comment by cojack** [comment]
@AJenbo sure, here you're b698f75117889b064a75cff3694f8b71

**Comment by AJenbo** [comment]
Hmm, that isn't a known valid hash for any of the known diabdat.mpq the file should be about 517MB.
