### ISSUE TITLE
gaming

### ISSUE THREAD

**Issue by lathithaharry** [d07RiV/diabloweb#38]
**Error message:**

    RangeError: Array buffer allocation failed
        at new ArrayBuffer (<anonymous>)
        at Uint8Array.slice (<anonymous>)
        at Object.draw_blit (https://kdata1.com/2019/08/diablo-web8/ec517037eb7f5fbaab67.worker.js:1:74708)
        at _api_draw_blit (https://kdata1.com/2019/08/diablo-web8/ec517037eb7f5fbaab67.worker.js:1:52456)
        at wasm-function[167]:455
        at wasm-function[1321]:1054
        at wasm-function[1324]:8
        at wasm-function[1243]:15
        at Object.a.dynCall_vii (https://kdata1.com/2019/08/diablo-web8/ec517037eb7f5fbaab67.worker.js:1:58718)
        at invoke_vii (https://kdata1.com/2019/08/diablo-web8/ec517037eb7f5fbaab67.worker.js:1:49234)

**Comment by d07RiV** [comment]
Sounds like an out of memory issue while trying to draw frames, quite strange.

What's that site though? I can't tell what version it is running.
