### ISSUE TITLE
the hell

### ISSUE THREAD

**Issue by catpat3** [d07RiV/diabloweb#497]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Retail)

**Error message:**
    
    Error: Main program archive: diabdat.mpq
        at Error (api/game.worker.js:86:10)
        at exit_error (api/Diablo.jscc:1645:135)
        at __Z14api_exit_errorPKc (wasm://wasm/005cc196:wasm-function[190]:0xfd01)
        at __Z9app_fatalPKcz (wasm://wasm/005cc196:wasm-function[192]:0xfd60)
        at _DApi_Init (wasm://wasm/005cc196:wasm-function[1277]:0xd4fc8)
        at apply (api/Diablo.jscc:2442:0)
        at https://d07riv.github.io/diabloweb/d2271be9a67638d3642f.worker.js?__WB_REVISION__=4115803155f6ffac29dc0498aae8c82f:1:79147
        at call (../node_modules/regenerator-runtime/runtime.js:45:0)
        at tryCatch (../node_modules/regenerator-runtime/runtime.js:264:0)
        at _invoke (../node_modules/regenerator-runtime/runtime.js:98:0)

**User agent:**

    Mozilla/5.0 (X11; CrOS x86_64 14150.87.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.124 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
The template. You appear to be running on a site with an old copy.

Duplicate: #172
