### ISSUE TITLE
Error al ingresar

### ISSUE THREAD

**Issue by Kushluk1989** [d07RiV/diabloweb#514]
#**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    RangeError: WebAssembly.Memory(): could not allocate memory
        at https://d07riv.github.io/diabloweb/8acc76fdb6ee253c485e.worker.js?__WB_REVISION__=71ba5fb375752153c9bc4a1c34faaa99:1:7685
        at https://d07riv.github.io/diabloweb/8acc76fdb6ee253c485e.worker.js?__WB_REVISION__=71ba5fb375752153c9bc4a1c34faaa99:1:30676
        at call (../node_modules/regenerator-runtime/runtime.js:45:0)
        at tryCatch (../node_modules/regenerator-runtime/runtime.js:264:0)
        at _invoke (../node_modules/regenerator-runtime/runtime.js:98:0)
        at arg (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:0)
        at asyncGeneratorStep (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:0)
        at https://d07riv.github.io/diabloweb/8acc76fdb6ee253c485e.worker.js?__WB_REVISION__=71ba5fb375752153c9bc4a1c34faaa99:1:31109
        at new Promise (<anonymous>)
        at m (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:21:0)

**User agent:**

    Mozilla/5.0 (Linux; Android 7.0; TRT-LX3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Mobile Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
You phone does not have enough memory, use the native build instead: https://play.google.com/store/apps/details?id=org.diasurgical.devilutionx
