### ISSUE TITLE
Diablo hellfire

### ISSUE THREAD

**Issue by Pally2008** [d07RiV/diabloweb#556]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Retail)

**Error message:**
    
    Error: Main program archive: diabdat.mpq
        at Error (api/game.worker.js:86:10)
        at exit_error (api/Diablo.jscc:1645:135)
        at __Z14api_exit_errorPKc (wasm://wasm/005cc196:wasm-function[190]:0xfd01)
        at __Z9app_fatalPKcz (wasm://wasm/005cc196:wasm-function[192]:0xfd60)
        at _DApi_Init (wasm://wasm/005cc196:wasm-function[1277]:0xd4fc8)
        at apply (api/Diablo.jscc:2442:0)
        at https://d07riv.github.io/diabloweb/d2271be9a67638d3642f.worker.js?__WB_REVISION__=4115803155f6ffac29dc0498aae8c82f:1:79147
        at call (../node_modules/regenerator-runtime/runtime.js:45:0)
        at tryCatch (../node_modules/regenerator-runtime/runtime.js:264:0)
        at _invoke (../node_modules/regenerator-runtime/runtime.js:98:0)

**User agent:**

    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 OPR/89.0.4447.98 (Edition std-1)

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
Hellfire is not supported. Use DevilutionX instead it has native Mac and hellfire support
