### ISSUE TITLE
Issue with Diabo 1 on Gameslol

### ISSUE THREAD

**Issue by Phantom093** [d07RiV/diabloweb#565]
**Description:**
[I was browsing this gaming website when I came across Diabo 1. I clicked on it but an error popped up. Anyone know what's up?]

**App version:**
DiabloWeb 1.0.39 (Retail)

**Error message:**
    
    Error: Main program archive: diabdat.mpq
        at Object.exit_error (api/game.worker.js:84:13)
        at self (api/Diablo.jscc:1645:135)
        at __Z14api_exit_errorPKc (wasm://wasm/005cc196:wasm-function[190]:0xfd01)
        at __Z9app_fatalPKcz (wasm://wasm/005cc196:wasm-function[192]:0xfd60)
        at _DApi_Init (wasm://wasm/005cc196:wasm-function[1277]:0xd4fc8)
        at a._DApi_Init (api/Diablo.jscc:2442:0)
        at https://en.gameslol.net/data/diablo/d2271be9a67638d3642f.worker.js:1:79125
        at c (../node_modules/regenerator-runtime/runtime.js:44:0)
        at state (../node_modules/regenerator-runtime/runtime.js:263:0)
        at n.<computed> (../node_modules/regenerator-runtime/runtime.js:98:0)

**User agent:**

    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0

**Save file:**
[It's not the save file but here's the website I was trying to use it on. https://en.gameslol.net/diablo-1-1634.html]

**Comment by AJenbo** [comment]
Don't play it via there website, they are violating the code license and host an outdated version
