### ISSUE TITLE
Cannot launch Diablo1 through https://www.gameslol.net/diablo-1-1634.html

### ISSUE THREAD

**Issue by MarianaBlo05** [d07RiV/diabloweb#571]
**Description:**
I got an  error notification when I tried to lauch Diablo 1.

**App version:**
DiabloWeb 1.0.39 (Retail)

**Error message:**
    
    Cannot read properties of null (reading 'buffer')
        at https://www.gameslol.net/data/diablo/static/js/main.0a18bc0c.chunk.js:2693:32
        at new Promise (<anonymous>)
        at https://www.gameslol.net/data/diablo/static/js/main.0a18bc0c.chunk.js:2579:15
        at call (../node_modules/regenerator-runtime/runtime.js:45:0)
        at tryCatch (../node_modules/regenerator-runtime/runtime.js:264:0)
        at _invoke (../node_modules/regenerator-runtime/runtime.js:98:0)
        at arg (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:0)
        at asyncGeneratorStep (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:0)

**User agent:**

--> Brave
    Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
Don't use gameslol.net, use the official site instead: https://d07riv.github.io/diabloweb/

Also since you are on Android why not use the native app instead: https://play.google.com/store/apps/details?id=org.diasurgical.devilutionx&hl=en&gl=US
