### ISSUE TITLE
Database is closed error while attempting to play shareware

### ISSUE THREAD

**Issue by fallenprogrammr** [d07RiV/diabloweb#580]
**Description:**
Clicked on the play shareware button, error occurred after loading was complete.

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    Database is closed
        at (unknown) (../node_modules/idb-kv-store/index.js:175:0)
        at (unknown) (../node_modules/idb-kv-store/index.js:105:0)
        at (unknown) (api/load_spawn.js:32:14)
        at obj (../node_modules/regenerator-runtime/runtime.js:45:0)
        at innerFn (../node_modules/regenerator-runtime/runtime.js:264:0)
        at arg (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:0)
        at gen (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:0)

**User agent:**

    Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Mobile/15E148 Safari/604.1

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
Where did you run the game from? You can also install the native version on iPhone using DevilutionX if you have access to a PC or Mac.
