### ISSUE TITLE
Error 1

### ISSUE THREAD

**Issue by Zaylpula** [d07RiV/diabloweb#589]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    invalid MPQ file
        at https://d07riv.github.io/diabloweb/static/js/main.0a18bc0c.chunk.js:1:34668
        at call (../node_modules/regenerator-runtime/runtime.js:45:0)
        at tryCatch (../node_modules/regenerator-runtime/runtime.js:264:0)
        at _invoke (../node_modules/regenerator-runtime/runtime.js:98:0)
        at arg (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:0)
        at asyncGeneratorStep (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:0)

**User agent:**

    Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]

Try using devilutionX instead it's in the app store and native doe android

**Comment by AJenbo** [comment]
Oh and select a valid mpq file obvious ...
