### ISSUE TITLE
diabo

### ISSUE THREAD

**Issue by yarokwkw** [d07RiV/diabloweb#598]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    TypeError: Cannot read property 'Memory' of undefined
        at https://d07riv.github.io/diabloweb/d2271be9a67638d3642f.worker.js:1:38591
        at https://d07riv.github.io/diabloweb/d2271be9a67638d3642f.worker.js:1:78234
        at call (../node_modules/regenerator-runtime/runtime.js:45:0)
        at tryCatch (../node_modules/regenerator-runtime/runtime.js:264:0)
        at _invoke (../node_modules/regenerator-runtime/runtime.js:98:0)
        at arg (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:0)
        at asyncGeneratorStep (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:0)

**User agent:**

    Mozilla/5.0 (Linux; Android 7.1.2; MXQ Pro Build/NHG47K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
Use DevilutionX on Android
