### ISSUE TITLE
Cannot read property 'entries' of undefined

### ISSUE THREAD

**Issue by cojack** [d07RiV/diabloweb#85]
**Description:**
I've just try to upload the DIABDAT.MPQ

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    Cannot read property 'entries' of undefined
        at https://d07riv.github.io/diabloweb/static/js/main.62369ba5.chunk.js:1:36174
        at call (../node_modules/regenerator-runtime/runtime.js:45:0)
        at tryCatch (../node_modules/regenerator-runtime/runtime.js:264:0)
        at _invoke (../node_modules/regenerator-runtime/runtime.js:98:0)
        at arg (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:0)
        at asyncGeneratorStep (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:0)

**User agent:**

    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/76.0.3809.87 Chrome/76.0.3809.87 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
Thanks for reporting this. Please report the MD5 of your and we will reopen the issue.
