### ISSUE TITLE
error to run Diabloweb in ubuntu 16.04

### ISSUE THREAD

**Issue by fortunatolf-tech** [d07RiV/diabloweb#96]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Retail)

**Error message:**
    
    Error: Main program archive: diabdat.mpq
        at Error (api/game.worker.js:86:10)
        at exit_error (api/Diablo.jscc:1645:135)
        at __Z14api_exit_errorPKc (wasm-function[190]:3)
        at __Z9app_fatalPKcz (wasm-function[192]:43)
        at _DApi_Init (wasm-function[1277]:202)
        at apply (api/Diablo.jscc:2442:0)
        at https://d07riv.github.io/diabloweb/b6959098d798174bd69f.worker.js?__WB_REVISION__=84295573488973f434291055ed9bbbff:1:79171
        at call (../node_modules/regenerator-runtime/runtime.js:45:0)
        at tryCatch (../node_modules/regenerator-runtime/runtime.js:264:0)
        at _invoke (../node_modules/regenerator-runtime/runtime.js:98:0)

**User agent:**

    Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/76.0.3809.100 Chrome/76.0.3809.100 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
What browser (and version)?
When does it crash?

**Comment by fortunatolf-tech** [comment]
My browser is Chromium 76.0.3809.100 (Versão oficial) Built on Ubuntu , running on Ubuntu 16.04 32 bits

**Comment by AJenbo** [comment]
Please describe what you were doing before the error occurred
